version: '3.1'
services:
   php-fpm:
      image: php:7.1-fpm
      volumes: 
        - ./conf.d:/etc/nginx/conf.d
        - ./www:/usr/share/nginx/html
   nginx:
      image: nginx
      links:
        - php-fpm:php  
      volumes: 
        - ./conf/nginx.conf:/etc/nginx/nginx.conf
        - ./conf.d:/etc/nginx/conf.d
        - ./www:/usr/share/nginx/html
      ports: 
        - 8080:80  